// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2Ci99vk2AWxHfCp33Bp0aQbSh4e8NRc',
    appId: '1:307189985628:android:a69186445bdfb8a40c9199',
    messagingSenderId: '307189985628',
    projectId: 'u-panel-2026',
    storageBucket: 'u-panel-2026.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUiWcvr6UyCVjv3OlQNxtFlEnfpRA4wGE',
    appId: '1:307189985628:web:0244a8c9bc9d4fed0c9199',
    messagingSenderId: '307189985628',
    projectId: 'u-panel-2026',
    authDomain: 'u-panel-2026.firebaseapp.com',
    storageBucket: 'u-panel-2026.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3yjQTwM8FXgu6L7qAz6aJL0jN3TXUvDU',
    appId: '1:307189985628:ios:d7d86402d47622630c9199',
    messagingSenderId: '307189985628',
    projectId: 'u-panel-2026',
    storageBucket: 'u-panel-2026.firebasestorage.app',
    iosBundleId: 'com.example.uPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUiWcvr6UyCVjv3OlQNxtFlEnfpRA4wGE',
    appId: '1:307189985628:web:21c285d4478770fd0c9199',
    messagingSenderId: '307189985628',
    projectId: 'u-panel-2026',
    authDomain: 'u-panel-2026.firebaseapp.com',
    storageBucket: 'u-panel-2026.firebasestorage.app',
  );

}