# Generated by Django 6.0.6 on 2026-06-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(db_index=True, max_length=255)),
                ('doc_id', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['collection', 'updated_at'], name='documents_a_collect_811631_idx')],
                'constraints': [models.UniqueConstraint(fields=('collection', 'doc_id'), name='documents_unique_collection_doc')],
            },
        ),
    ]
